version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: benjaminli
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
